          <ul class="nav trophy-nav">
            <li><a href="OlgaJekyll.php"		> Olga Jekyll		</a></li>
            <li><a href="Keith Mann.php"		> Keith Mann		</a></li>		
            <li><a href="VictorManuge.php"		> Victor Manuge		</a></li>       
            <li><a href="DavidEccleston.php"	> David Eccleston	</a></li>       
            <li><a href="S_Temple.php"			> S Temple			</a></li>       
            <li><a href="FrankHogg.php"			> Frank Hogg		</a></li>   
            <li><a href="MurrayGoodman.php"		> Murray Goodman	</a></li>   
            <li><a href="NeilSmith.php"			> Neil Smith		</a></li>   
            <li><a href="ArthurReveKamp.php"	> Arthur Reve Kamp	</a></li>       
            <li><a href="Maxwell Perkins.php"	> Maxwell Perkins	</a></li>       
            <li><a href="Hubert Hayston.php"	> Hubert Hayston	</a></li>       
            <li><a href="Florence Andrews.php"	> Florence Andrews	</a></li>       
            <li><a href="Spackman.php"			> _Spackman			</a></li>       
			<li><a href="Fiona Brown.php"		> Fiona Brown		</a></li>       
			<li><a href="Steve L. Clarke.php"   > Steve L. Clarke   </a></li>      
			<li><a href="Diane Swain.php"       > Diane Swain       </a></li>      
			<li><a href="David Shillito.php"    > David Shillito    </a></li>      
			<li><a href="Geoff Low.php"         > Geoff Low         </a></li>      
			<li><a href="Carville Stewart.php"  > Carville Stewart  </a></li>      
			<li><a href="Rob Sheard.php"        > Rob Sheard        </a></li>      
			<li><a href="Barry Cameron.php"     > Barry Cameron     </a></li>      
			<li><a href="Martin Brill.php"      > Martin Brill      </a></li>      
          </ul>
